---
- name: Configure a Linux host specifically for the GNOME desktop environment 
  hosts: localhost
  become: true
  roles:
     - ../roles/nvidia
     - ../roles/git-config
     - ../roles/obsidian
     - ../roles/codium #Free/Libre Open Source Software Binaries of VS Code
     - ../roles/spotify
